#!/usr/bin/env bash

docker compose down
mvn clean package
docker compose up -d
sleep 1
echo "ServerDeployed in http://localhost:8080/mavenproject1-1.0-SNAPSHOT"

docker exec -it glassfish-with-docker /opt/glassfish7/bin/asadmin start-domain
docker exec -it glassfish-with-docker /opt/glassfish7/bin/asadmin deploy --force /var/my-jakarta-app/target/mavenproject1-1.0-SNAPSHOT.war
